function compile_loess()

if ispc
    mex('-I C:\dev\eigen-eigen-5a0156e40feb',...        % Eigen headers
        '-I C:\dev\CGAL-4.11\include',...               % CGAL headers
        '-I C:\dev\CGAL-4.11\build\include',...         % CGAL headers generated by cmake during compilation of CGAL
        '-I C:\local\boost_1_65_1',...                  % Boost headers
        '-L C:\dev\CGAL-4.11\build\lib',...             % CGAL compiled libraries
        '-L C:\local\boost_1_65_1\lib64-msvc-12.0',...  % Boost libraries
        '-lmwservices',...
        '-lmwbuiltinsutil',...
        'loess.cpp')
elseif isunix
    mex -v CXXFLAGS='$CXXFLAGS -Wall -std=c++17 -static' -DCGAL_EIGEN3_ENABLED -DMATLAB_MEXCMD_RELEASE=R2017b -I/usr/include/eigen3/  loess.cpp
end

end
